// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReniecRamos.Data;

#nullable disable

namespace ReniecRamos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReniecRamos.Models.Citizen", b =>
                {
                    b.Property<int>("CitizenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CitizenId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BirthUbigeoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CivilStatusId")
                        .HasColumnType("int");

                    b.Property<string>("CurrentAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentUbigeoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecondLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CitizenId");

                    b.HasIndex("BirthUbigeoId");

                    b.HasIndex("CivilStatusId");

                    b.HasIndex("CurrentUbigeoId");

                    b.HasIndex("DocumentTypeId");

                    b.ToTable("Citizens");
                });

            modelBuilder.Entity("ReniecRamos.Models.CivilStatus", b =>
                {
                    b.Property<int>("CivilStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CivilStatusId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CivilStatusId");

                    b.ToTable("CivilStatuses");

                    b.HasData(
                        new
                        {
                            CivilStatusId = 1,
                            Description = "Soltero(a)"
                        },
                        new
                        {
                            CivilStatusId = 2,
                            Description = "Casado(a)"
                        },
                        new
                        {
                            CivilStatusId = 3,
                            Description = "Divorciado(a)"
                        },
                        new
                        {
                            CivilStatusId = 4,
                            Description = "Viudo(a)"
                        });
                });

            modelBuilder.Entity("ReniecRamos.Models.DocumentType", b =>
                {
                    b.Property<int>("DocumentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentTypeId"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentTypeId");

                    b.ToTable("DocumentTypes");

                    b.HasData(
                        new
                        {
                            DocumentTypeId = 1,
                            Abbreviation = "DNI",
                            Description = "Documento Nacional de Identidad"
                        },
                        new
                        {
                            DocumentTypeId = 2,
                            Abbreviation = "PAS",
                            Description = "Pasaporte"
                        },
                        new
                        {
                            DocumentTypeId = 3,
                            Abbreviation = "CE",
                            Description = "Carnet de Extranjería"
                        });
                });

            modelBuilder.Entity("ReniecRamos.Models.Procedure", b =>
                {
                    b.Property<int>("ProcedureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProcedureId"));

                    b.Property<int>("CitizenId")
                        .HasColumnType("int");

                    b.Property<string>("ProcedureType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProcedureId");

                    b.HasIndex("CitizenId");

                    b.ToTable("Procedures");
                });

            modelBuilder.Entity("ReniecRamos.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "Administrator"
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "Assistant"
                        });
                });

            modelBuilder.Entity("ReniecRamos.Models.Ubigeo", b =>
                {
                    b.Property<string>("UbigeoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UbigeoId");

                    b.ToTable("Ubigeos");

                    b.HasData(
                        new
                        {
                            UbigeoId = "150101",
                            Department = "Lima",
                            District = "Lima",
                            Province = "Lima"
                        },
                        new
                        {
                            UbigeoId = "150122",
                            Department = "Lima",
                            District = "Miraflores",
                            Province = "Lima"
                        },
                        new
                        {
                            UbigeoId = "150142",
                            Department = "Lima",
                            District = "Surquillo",
                            Province = "Lima"
                        },
                        new
                        {
                            UbigeoId = "070101",
                            Department = "Callao",
                            District = "Callao",
                            Province = "Callao"
                        },
                        new
                        {
                            UbigeoId = "070106",
                            Department = "Callao",
                            District = "Ventanilla",
                            Province = "Callao"
                        },
                        new
                        {
                            UbigeoId = "040101",
                            Department = "Arequipa",
                            District = "Arequipa",
                            Province = "Arequipa"
                        },
                        new
                        {
                            UbigeoId = "080101",
                            Department = "Cusco",
                            District = "Cusco",
                            Province = "Cusco"
                        },
                        new
                        {
                            UbigeoId = "130101",
                            Department = "La Libertad",
                            District = "Trujillo",
                            Province = "Trujillo"
                        },
                        new
                        {
                            UbigeoId = "140101",
                            Department = "Lambayeque",
                            District = "Chiclayo",
                            Province = "Chiclayo"
                        },
                        new
                        {
                            UbigeoId = "190101",
                            Department = "Pasco",
                            District = "Chaupimarca",
                            Province = "Pasco"
                        });
                });

            modelBuilder.Entity("ReniecRamos.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            FullName = "Jhon Administrador",
                            IsActive = true,
                            PasswordHash = new byte[] { 36, 50, 97, 36, 49, 49, 36, 109, 57, 78, 57, 56, 88, 122, 89, 57, 46, 75, 115, 116, 72, 108, 71, 46, 71, 56, 118, 55, 117, 56, 86, 118, 53, 90, 112, 54, 77, 56, 76, 112, 55, 83, 54, 82, 53, 81, 52, 80, 51, 79, 50, 78, 49, 77, 48, 76, 57, 75, 56, 74 },
                            RoleId = 1,
                            Username = "jhonAd"
                        },
                        new
                        {
                            UserId = 2,
                            FullName = "Jhon Asistente",
                            IsActive = true,
                            PasswordHash = new byte[] { 36, 50, 97, 36, 49, 49, 36, 109, 57, 78, 57, 56, 88, 122, 89, 57, 46, 75, 115, 116, 72, 108, 71, 46, 71, 56, 118, 55, 117, 56, 86, 118, 53, 90, 112, 54, 77, 56, 76, 112, 55, 83, 54, 82, 53, 81, 52, 80, 51, 79, 50, 78, 49, 77, 48, 76, 57, 75, 56, 74 },
                            RoleId = 2,
                            Username = "jhonAsis"
                        });
                });

            modelBuilder.Entity("ReniecRamos.Models.Citizen", b =>
                {
                    b.HasOne("ReniecRamos.Models.Ubigeo", "BirthPlace")
                        .WithMany()
                        .HasForeignKey("BirthUbigeoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReniecRamos.Models.CivilStatus", "CivilStatus")
                        .WithMany()
                        .HasForeignKey("CivilStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReniecRamos.Models.Ubigeo", "ResidencePlace")
                        .WithMany()
                        .HasForeignKey("CurrentUbigeoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReniecRamos.Models.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BirthPlace");

                    b.Navigation("CivilStatus");

                    b.Navigation("DocumentType");

                    b.Navigation("ResidencePlace");
                });

            modelBuilder.Entity("ReniecRamos.Models.Procedure", b =>
                {
                    b.HasOne("ReniecRamos.Models.Citizen", "Citizen")
                        .WithMany()
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Citizen");
                });

            modelBuilder.Entity("ReniecRamos.Models.User", b =>
                {
                    b.HasOne("ReniecRamos.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ReniecRamos.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
